import { site } from '$lib/config';

// Automatically generated by `npm run build` / dev server at request time.
export const prerender = true;

/** @type {import('./$types').RequestHandler} */
export function GET() {
	const body = `User-agent: *
Allow: /
Disallow: /404

Sitemap: ${site.url}/sitemap.xml
`;

	return new Response(body, {
		headers: {
			'Content-Type': 'text/plain; charset=utf-8'
		}
	});
}